name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare .env
      run: cp env.sample .env
    - name: Build the Docker image
      run: docker compose up -d
    - name: Wait for HTTP 200 response
      uses: cygnetdigital/wait_for_response@v2.0.0
      with:
        url: 'https://localhost:7007/'
        responseCode: '200'
        timeout: 2000
        interval: 500
